name: pmnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch>=2.0.0
      - rdkit>=2022.9.1
      - pandas>=1.5.0
      - numpy>=1.23.0
      - matplotlib>=3.6.0
      - seaborn>=0.12.0
      - scikit-learn>=1.1.0
      - biopython>=1.80
      - openbabel>=3.1.0
